# Generated by Django 4.1.1 on 2022-10-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_intrested_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirm'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
    ]
