# Generated by Django 4.1.1 on 2022-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invitation_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Official', (('Company Meeting', 'Company Meeting'), ('Exhibition', 'Exhibition'), ('Concert', 'Concert'), ('Gala', 'Gala'), ('Bal', 'Bal'), ('March', 'March'), ('Show', 'Show'), ('Others', 'Others'))), ('Unofficial', (('Birthday Party', 'Birthday Party'), ('Boozing', 'Boozing'), ('House Party', 'House Party'), ('Others', 'Others'), ('Celebration', 'Celebration'), ('Family Meeting', 'Family Meeting'), ('Others', 'Others')))], max_length=50, null=True, verbose_name='Category  '),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(null=True, verbose_name='End time  '),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(null=True, verbose_name='Is free'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(null=True, verbose_name='Is open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=60, null=True, verbose_name='Location  '),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(null=True, verbose_name='Start time'),
        ),
    ]
