# Generated by Django 4.1.1 on 2022-11-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_category_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='status',
        ),
    ]
