# Generated by Django 4.1.1 on 2022-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Official', (('Company Meeting', 'Company Meeting'), ('Exhibition', 'Exhibition'), ('Concert', 'Concert'), ('Gala', 'Gala'), ('Bal', 'Bal'), ('March', 'March'), ('Show', 'Show'), ('Others', 'Others'))), ('Unofficial', (('Birthday Party', 'Birthday Party'), ('Boozing', 'Boozing'), ('House Party', 'House Party'), ('Celebration', 'Celebration'), ('Family Meeting', 'Family Meeting'), ('Others', 'Others')))], max_length=50, null=True, verbose_name='Category  '),
        ),
    ]
