# Generated by Django 4.1.1 on 2022-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_paricipants_invite',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
