# Generated by Django 4.1.1 on 2023-02-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_can_paricipants_invite_event_can_participants_invite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
    ]
