# Generated by Django 4.1.1 on 2023-02-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_body_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isSpecial',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
