# Generated by Django 4.1.1 on 2022-12-01 11:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default='model.png', null=True, upload_to=main.models.MyUser.user_directory_path),
        ),
    ]
